# Generated by Django 4.2.3 on 2023-07-15 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbscontent', models.TextField(max_length=100, verbose_name='掲示板')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('name_en', models.CharField(max_length=10, verbose_name='カテゴリ名英語')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_top_title', models.CharField(max_length=25, verbose_name='トップタイトル')),
                ('home_sub_title', models.CharField(max_length=25, verbose_name='サブタイトル')),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_keywords', models.CharField(max_length=30, verbose_name='metaタグ(name="keywords")')),
                ('meta_description', models.CharField(max_length=120, verbose_name='metaタグ(name="description")')),
                ('meta_prop_ogTitle', models.CharField(max_length=30, verbose_name='metaタグ(property="og:title")')),
                ('meta_prop_ogImage', models.ImageField(blank=True, upload_to='images/', verbose_name='metaタグ(property="og:image")')),
                ('meta_prop_ogWidth', models.PositiveSmallIntegerField(verbose_name='metaタグ(property="og:image:width")')),
                ('meta_prop_ogHeight', models.PositiveSmallIntegerField(verbose_name='metaタグ(property="og:image:height")')),
                ('meta_prop_ogDescription', models.CharField(max_length=120, verbose_name='metaタグ(property="og:description")')),
                ('meta_prop_ogSiteName', models.CharField(max_length=30, verbose_name='metaタグ(property="og:site_name")')),
                ('meta_prop_ogUrl', models.URLField(verbose_name='metaタグ(property="og:url")')),
                ('meta_twi_imgSrc', models.ImageField(blank=True, upload_to='images/', verbose_name='metaタグ(name="twitter:image:src")')),
                ('meta_twi_title', models.CharField(max_length=120, verbose_name='metaタグ(name="twitter:title")')),
                ('page_title', models.CharField(max_length=25, verbose_name='ページタイトル')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('description', models.TextField(max_length=100, verbose_name='概要')),
                ('content', models.TextField(blank=True, max_length=10000, verbose_name='内容')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.post', verbose_name='投稿')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Likeしたユーザー')),
            ],
        ),
    ]
