# Generated by Django 4.2.3 on 2023-07-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='home_sub_title',
            field=models.CharField(blank=True, max_length=25, verbose_name='サブタイトル'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_prop_ogDescription',
            field=models.CharField(blank=True, max_length=120, verbose_name='metaタグ(property="og:description")'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_prop_ogHeight',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='metaタグ(property="og:image:height")'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_prop_ogSiteName',
            field=models.CharField(blank=True, max_length=30, verbose_name='metaタグ(property="og:site_name")'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_prop_ogUrl',
            field=models.URLField(blank=True, verbose_name='metaタグ(property="og:url")'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_prop_ogWidth',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='metaタグ(property="og:image:width")'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_twi_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='metaタグ(name="twitter:title")'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='page_title',
            field=models.CharField(blank=True, max_length=25, verbose_name='ページタイトル'),
        ),
    ]
