# Generated by Django 3.1.7 on 2021-05-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210515_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='bbscontent',
            field=models.TextField(max_length=100, verbose_name='掲示板'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=10000, verbose_name='内容'),
        ),
    ]
