# Generated by Django 3.1.7 on 2021-05-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_layout_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='page_title',
            field=models.CharField(default=1, max_length=25, verbose_name='ページタイトル'),
            preserve_default=False,
        ),
    ]
